### ISSUE TITLE
build fails because of native routine registration

### ISSUE THREAD

**Issue by barryrowlingson** [stpp-GitHub-community/stpp#2]
Running devtools::check("stpp") fails with a NOTE:

```
* checking compiled code ... NOTE
File ‘stpp/libs/stpp.so’:
  Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’

It is good practice to register native routines and to disable symbol
search.

```

**Comment by barryrowlingson** [comment]
init.c generated via:
 
`tools::package_native_routine_registration_skeleton("stpp")`

**Comment by barryrowlingson** [comment]
Can someone check their local build? I definitely don't get an error on my Linux build, but the appveyor build does:

https://ci.appveyor.com/project/barryrowlingson/stpp

**Comment by frajaroco** [comment]
Hi Barry,

For me happen the same, under Linux everything is ok but for Windows still have the NOTE using the R version 3.4.2 (2017-09-28) -- "Short Summer".

**Comment by frajaroco** [comment]
I have also tried following the suggestions in the links:

- http://dirk.eddelbuettel.com/blog/2017/04/30/#006_easiest_package_registration
- http://dirk.eddelbuettel.com/blog/2017/03/30/#002_even_easier_package_registration
- http://dirk.eddelbuettel.com/blog/2017/03/29/#001_easy_package_registration
- https://stackoverflow.com/questions/43101032/fortran-code-and-found-no-calls-to-r-registerroutines-r-usedynamicsymbols
- https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Registering-native-routines

But the problem continues!

**Comment by barryrowlingson** [comment]
Are you getting the messages about objdump.exe?


```
* checking compiled code ... NOTE
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
File 'stpp/libs/i386/stpp.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'
It is good practice to register native routines and to disable symbol
search.
```

I get this on appveyor. R needs objdump.exe to see if the R_registerRoutines is being called, but on appveyor with the current config this isn't found. 

I've just tried tweaking the path which might now find objdump.exe

related issue:

https://github.com/krlmlr/r-appveyor/issues/94

**Comment by frajaroco** [comment]
No, this not happen for my!

**Comment by barryrowlingson** [comment]
I've changed the path in the appveyor.yml and it works now without errors or notes on appveyor.

https://ci.appveyor.com/project/barryrowlingson/stpp/build/1.0.4

**Comment by frajaroco** [comment]
Yes, thanks!
